---
downloads: ~/.ansible-downloads/

configure_dotfiles: no
configure_sudoers: yes
configure_terminal: yes
configure_osx: yes

dotfiles_repo: https://github.com/geerlingguy/dotfiles.git
dotfiles_repo_accept_hostkey: yes
dotfiles_repo_local_destination: ~/Dropbox/Development/GitHub/dotfiles
dotfiles_files:
  - .bash_profile
  - .gitignore
  - .inputrc
  - .osx
  - .vimrc

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - ag
  - autoconf
  - bash-completion
  - chromedriver
  - cowsay
  - dockutil
  - doxygen
  - gettext
  - gifsicle
  - git
  - go
  - gpg
  - hub
  - httpie
  - iperf
  - libevent
  - sqlite
  - mcrypt
  - nmap
  - node
  - nvm
  - openssl
  - packer
  - pv
  - readline
  - ssh-copy-id
  - terraform
  - tree
  - wget
  - wrk

homebrew_taps:
  - homebrew/core
  - caskroom/cask
  - homebrew/php

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - arduino
  - bbedit
  - burn
  - chefdk
  - cleanmymac
  - cyberduck
  - disk-inventory-x
  - divvy
  - docker
  - dropbox
  - evernote
  - firefox
  - github-desktop
  - google-chrome
  - google-drive
  - google-earth
  - gpg-sync
  - gpgtools
  - graphicconverter
  - handbrake
  - keybase
  - istumbler
  - lastpass
  - omnigraffle
  - rekordbox
  - remember-the-milk
  - slack
  - skype
  - sublime-text
  - tftpserver
  - the-unarchiver
  - thunderbird
  - transmit
  - transmission
  - vagrant
  - vnc-viewer
  - virtualbox
  - wireshark
  - xquartz
  - zoomus

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: []
mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
  # - name: drush
  #   state: present # present/absent, default: present
  #   version: "^8.1" # default: N/A
gem_packages: []
  # - name: bundler
  #   state: present # present/absent/latest, default: present
  #   version: "~> 1.15.1" # default: N/A
npm_packages: []
  # - name: webpack
  #   state: present # present/absent/latest, default: present
  #   version: "^2.6" # default: N/A
pip_packages: []
  # - name: mkdocs
  #   state: present # present/absent/latest, default: present
  #   version: "0.16.3" # default: N/A

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []

#
# Dockutil
# To manage dock items.

dockitems_disabled:
  - Launchpad
  - Mail
  - Contacts
  - Notes
  - Reminders
  - Maps
  - Photos
  - iBooks
  - System Preferences
  - Calendar
  - Siri
  - Keynote
  - Pages
  - Numbers
  - App Store

dockitems_enabled:
  - name: Google Chrome
    path: "/Applications/Google Chrome.app"
    pos: 1
  - name: Firefox
    path: "/Applications/Firefox.app"
    pos: 2
  - name: Thunderbird
    path: "/Applications/Thunderbird.app"
    pos: 3
  - name: Slack
    path: "/Applications/Slack.app"
    pos: 4
  - name: Evernote
    path: "/Applications/Evernote.app"
    pos: 5
  - name: Terminal
    path: "/Applications/Utilities/Terminal.app"
    pos: 6
  - name: Preview
    path: "/Applications/Preview.app"
    pos: 7
